### ISSUE TITLE
After a merge to 'main', the branch is auto deleted

### ISSUE THREAD

**Issue by yamori** [yamori/k8e-collab#13]
good first github repo 'config' Issue, so you can see what's possible within a repo's settings.

**Comment by zerske** [comment]
@yamori - I think you'll need to check this setting? 

Personal repos have one owner and can only add "collaborators", but the [setting for automatically deleting head branches](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-the-automatic-deletion-of-branches) requires admin access.
