### ISSUE TITLE
Cleanup index.js

### ISSUE THREAD

**Issue by yamori** [yamori/k8e-collab#4]
... so that it doesn't look like the boilerplate/start nextJS app.  Doesn't need a lot of content, just to remove the 'hey these are nextJS features' so that index.js is a nice clean slate for us to start.

**Comment by yamori** [comment]
... and add some basic image, that will reside in the `public` directoy, have it display on the root page

**Comment by yamori** [comment]
any chance you could have a PR for this before our chat tomorrow?

**Comment by zerske** [comment]
Yep! Planning on looking at this today on my lunch/after work.
